<?php

namespace Database\Seeders;

use Illuminate\Support\Facades\DB;

class CategoriesTableSeeder
{
    public static function getCategories()
    {
        $categories = array(
            array('id' => '1','name' => 'Diary Products','photo' => 'category-default.jpg','slug' => 'diary-products','description' => 'Milk, cheese, butter, yogurt, cream, ice cream','group_by' => 'Food & Beverages','is_active' => '1','created_at' => '2025-05-12 13:32:22','updated_at' => '2025-05-12 15:40:22'),
            array('id' => '2','name' => 'Fresh Produce','photo' => 'category-default.jpg','slug' => 'fresh-produce','description' => 'Fruits, vegetables, herbs','group_by' => 'Food & Beverages','is_active' => '1','created_at' => '2025-05-18 20:33:26','updated_at' => '2025-05-18 20:33:26'),
            array('id' => '3','name' => 'Packaged Snacks','photo' => 'category-default.jpg','slug' => 'packaged-snacks','description' => 'Chips, crackers, cookies, candy, granola bars, popcorn','group_by' => 'Food & Beverages','is_active' => '1','created_at' => '2025-05-18 20:33:26','updated_at' => '2025-05-18 20:33:26'),
            array('id' => '4','name' => 'Canned Goods','photo' => 'category-default.jpg','slug' => 'canned-goods','description' => 'Soups, vegetables, fruits, meats, ready-to-eat meals','group_by' => 'Food & Beverages','is_active' => '1','created_at' => '2025-05-18 20:33:26','updated_at' => '2025-05-18 20:33:26'),
            array('id' => '5','name' => 'Frozen Foods','photo' => 'category-default.jpg','slug' => 'frozen-foods','description' => 'Frozen vegetables, fruits, ready-to-eat meals, frozen pizza, ice cream','group_by' => 'Food & Beverages','is_active' => '1','created_at' => '2025-05-18 20:33:26','updated_at' => '2025-05-18 20:33:26'),
            array('id' => '6','name' => 'Meat & Seafood','photo' => 'category-default.jpg','slug' => 'meat-seafood','description' => 'Fresh meat (beef, pork, chicken), processed meats (sausages, hot dogs), fish, seafood, deli meats','group_by' => 'Food & Beverages','is_active' => '1','created_at' => '2025-05-18 20:33:26','updated_at' => '2025-05-18 20:33:26'),
            array('id' => '7','name' => 'Bakery Products','photo' => 'category-default.jpg','slug' => 'bakery-products','description' => 'Bread, rolls, cakes, muffins, pastries, cookies','group_by' => 'Food & Beverages','is_active' => '1','created_at' => '2025-05-18 20:33:26','updated_at' => '2025-05-18 20:33:26'),
            array('id' => '8','name' => 'Beverages','photo' => 'category-default.jpg','slug' => 'beverages','description' => 'Juices, soft drinks, alcoholic beverages (wine, beer, spirits), bottled water, energy drinks, teas, coffees','group_by' => 'Food & Beverages','is_active' => '1','created_at' => '2025-05-18 20:33:26','updated_at' => '2025-05-18 20:33:26'),
            array('id' => '9','name' => 'Baby Food and Formula','photo' => 'category-default.jpg','slug' => 'baby-food-formula','description' => 'Baby jars, purees, formula, snacks','group_by' => 'Food & Beverages','is_active' => '1','created_at' => '2025-05-18 20:33:26','updated_at' => '2025-05-18 20:33:26'),
            array('id' => '10','name' => 'Spices & Seasonings','photo' => 'category-default.jpg','slug' => 'spices-seasonings','description' => 'Ground spices, seasoning mixes, herbs','group_by' => 'Food & Beverages','is_active' => '1','created_at' => '2025-05-18 20:33:26','updated_at' => '2025-05-18 20:33:26'),
            array('id' => '11','name' => 'Condiments & Sauces','photo' => 'category-default.jpg','slug' => 'condiments-sauces','description' => 'Ketchup, mustard, mayonnaise, salad dressings, soy sauce, hot sauce','group_by' => 'Food & Beverages','is_active' => '1','created_at' => '2025-05-18 20:33:26','updated_at' => '2025-05-18 20:33:26'),
            array('id' => '12','name' => 'Processed Foods','photo' => 'category-default.jpg','slug' => 'processed-foods','description' => 'Instant noodles, frozen dinners, canned chili, prepared meals','group_by' => 'Food & Beverages','is_active' => '1','created_at' => '2025-05-18 20:33:26','updated_at' => '2025-05-18 20:33:26'),
            array('id' => '13','name' => 'Breakfast Foods','photo' => 'category-default.jpg','slug' => 'breakfast-foods','description' => 'Cereals, oatmeal, pancake mix, granola','group_by' => 'Food & Beverages','is_active' => '1','created_at' => '2025-05-18 20:33:26','updated_at' => '2025-05-18 20:33:26'),
            array('id' => '14','name' => 'Confectionery & Sweets','photo' => 'category-default.jpg','slug' => 'confectionery-sweets','description' => 'Chocolates, chewing gum, hard candy, gummies, mints','group_by' => 'Food & Beverages','is_active' => '1','created_at' => '2025-05-18 20:33:26','updated_at' => '2025-05-18 20:33:26'),
            array('id' => '15','name' => 'Medications & Supplements','photo' => 'category-default.jpg','slug' => 'medications-supplements','description' => 'Prescription medications, over-the-counter medications (pain relievers, cold medicines), vitamins, herbal supplements, probiotics','group_by' => 'Health & Wellness Products','is_active' => '1','created_at' => '2025-05-18 20:33:59','updated_at' => '2025-05-18 20:33:59'),
            array('id' => '16','name' => 'Over-the-counter Remedies','photo' => 'category-default.jpg','slug' => 'over-the-counter-remedies','description' => 'Cough syrup, antacids, allergy medicines','group_by' => 'Health & Wellness Products','is_active' => '1','created_at' => '2025-05-18 20:33:59','updated_at' => '2025-05-18 20:33:59'),
            array('id' => '17','name' => 'Personal Care Products','photo' => 'category-default.jpg','slug' => 'personal-care-products','description' => 'Deodorants, shampoos, conditioners, body washes, hair sprays','group_by' => 'Health & Wellness Products','is_active' => '1','created_at' => '2025-05-18 20:33:59','updated_at' => '2025-05-18 20:33:59'),
            array('id' => '18','name' => 'Skin Care Products','photo' => 'category-default.jpg','slug' => 'skin-care-products','description' => 'Creams, lotions, serums, sunscreens, face masks, acne treatments','group_by' => 'Health & Wellness Products','is_active' => '1','created_at' => '2025-05-18 20:33:59','updated_at' => '2025-05-18 20:33:59'),
            array('id' => '19','name' => 'Oral Care','photo' => 'category-default.jpg','slug' => 'oral-care','description' => 'Toothpaste, mouthwash, floss, teeth whitening products','group_by' => 'Health & Wellness Products','is_active' => '1','created_at' => '2025-05-18 20:33:59','updated_at' => '2025-05-18 20:33:59'),
            array('id' => '20','name' => 'Feminine Care','photo' => 'category-default.jpg','slug' => 'feminine-care','description' => 'Sanitary pads, tampons, menstrual cups','group_by' => 'Health & Wellness Products','is_active' => '1','created_at' => '2025-05-18 20:33:59','updated_at' => '2025-05-18 20:33:59'),
            array('id' => '21','name' => 'First Aid Products','photo' => 'category-default.jpg','slug' => 'first-aid-products','description' => 'Band-aids, antiseptics, hydrogen peroxide, gauze, ointments, ice packs','group_by' => 'Health & Wellness Products','is_active' => '1','created_at' => '2025-05-18 20:33:59','updated_at' => '2025-05-18 20:33:59'),
            array('id' => '22','name' => 'Contact Lens Solutions','photo' => 'category-default.jpg','slug' => 'contact-lens-solutions','description' => 'Cleaning solutions, lubricating eye drops, lens disinfectants','group_by' => 'Health & Wellness Products','is_active' => '1','created_at' => '2025-05-18 20:33:59','updated_at' => '2025-05-18 20:33:59'),
            array('id' => '23','name' => 'Makeup','photo' => 'category-default.jpg','slug' => 'makeup','description' => 'Foundations, mascaras, eyeliners, lipsticks, lip glosses, blushes, eyeshadows, powders, makeup removers','group_by' => 'Cosmetics & Beauty Products','is_active' => '1','created_at' => '2025-05-18 20:34:17','updated_at' => '2025-05-18 20:34:17'),
            array('id' => '24','name' => 'Nail Care','photo' => 'category-default.jpg','slug' => 'nail-care','description' => 'Nail polish, nail polish removers, nail treatments, cuticle oils','group_by' => 'Cosmetics & Beauty Products','is_active' => '1','created_at' => '2025-05-18 20:34:17','updated_at' => '2025-05-18 20:34:17'),
            array('id' => '25','name' => 'Skin Care Products','photo' => 'category-default.jpg','slug' => 'beauty-skin-care','description' => 'Moisturizers, exfoliators, toners, face masks, cleansers, anti-aging creams','group_by' => 'Cosmetics & Beauty Products','is_active' => '1','created_at' => '2025-05-18 20:34:17','updated_at' => '2025-05-18 20:34:17'),
            array('id' => '26','name' => 'Hair Care Products','photo' => 'category-default.jpg','slug' => 'hair-care-products','description' => 'Shampoos, conditioners, hair styling products, hair oils, hair dyes, hair treatments','group_by' => 'Cosmetics & Beauty Products','is_active' => '1','created_at' => '2025-05-18 20:34:17','updated_at' => '2025-05-18 20:34:17'),
            array('id' => '27','name' => 'Fragrances','photo' => 'category-default.jpg','slug' => 'fragrances','description' => 'Perfumes, colognes, body sprays','group_by' => 'Cosmetics & Beauty Products','is_active' => '1','created_at' => '2025-05-18 20:34:17','updated_at' => '2025-05-18 20:34:17'),
            array('id' => '28','name' => 'Shaving & Grooming','photo' => 'category-default.jpg','slug' => 'shaving-grooming','description' => 'Shaving cream, razors, aftershaves, beard oils','group_by' => 'Cosmetics & Beauty Products','is_active' => '1','created_at' => '2025-05-18 20:34:17','updated_at' => '2025-05-18 20:34:17'),
            array('id' => '29','name' => 'Laundry Detergents','photo' => 'category-default.jpg','slug' => 'laundry-detergents','description' => 'Liquid detergents, powder detergents, fabric softeners, bleach','group_by' => 'Cleaning & Household Products','is_active' => '1','created_at' => '2025-05-18 20:34:39','updated_at' => '2025-05-18 20:34:39'),
            array('id' => '30','name' => 'Cleaning Products','photo' => 'category-default.jpg','slug' => 'cleaning-products','description' => 'All-purpose cleaners, disinfectants, glass cleaners, toilet cleaners, degreasers, floor cleaners','group_by' => 'Cleaning & Household Products','is_active' => '1','created_at' => '2025-05-18 20:34:39','updated_at' => '2025-05-18 20:34:39'),
            array('id' => '31','name' => 'Air Fresheners & Odor Removers','photo' => 'category-default.jpg','slug' => 'air-fresheners','description' => 'Sprays, candles, diffusers, plug-ins','group_by' => 'Cleaning & Household Products','is_active' => '1','created_at' => '2025-05-18 20:34:39','updated_at' => '2025-05-18 20:34:39'),
            array('id' => '32','name' => 'Pest Control','photo' => 'category-default.jpg','slug' => 'pest-control','description' => 'Pesticides, bug repellents, flea treatments','group_by' => 'Cleaning & Household Products','is_active' => '1','created_at' => '2025-05-18 20:34:39','updated_at' => '2025-05-18 20:34:39'),
            array('id' => '33','name' => 'Paper Products','photo' => 'category-default.jpg','slug' => 'paper-products','description' => 'Toilet paper, paper towels, napkins, tissues','group_by' => 'Cleaning & Household Products','is_active' => '1','created_at' => '2025-05-18 20:34:39','updated_at' => '2025-05-18 20:34:39'),
            array('id' => '34','name' => 'Batteries','photo' => 'category-default.jpg','slug' => 'household-batteries','description' => 'Alkaline, lithium-ion, rechargeable batteries (for devices like cameras, remotes, etc.)','group_by' => 'Cleaning & Household Products','is_active' => '1','created_at' => '2025-05-18 20:34:39','updated_at' => '2025-05-18 20:34:39'),
            array('id' => '35','name' => 'Trash Bags & Storage Bags','photo' => 'category-default.jpg','slug' => 'trash-storage-bags','description' => 'Garbage bags, Ziploc bags, freezer bags, vacuum-seal bags','group_by' => 'Cleaning & Household Products','is_active' => '1','created_at' => '2025-05-18 20:34:39','updated_at' => '2025-05-18 20:34:39'),
            array('id' => '36','name' => 'Scented & Cleaning Candles','photo' => 'category-default.jpg','slug' => 'scented-candles','description' => 'Wax melts, scented candles, air freshening gels','group_by' => 'Cleaning & Household Products','is_active' => '1','created_at' => '2025-05-18 20:34:39','updated_at' => '2025-05-18 20:34:39'),
            array('id' => '37','name' => 'Pet Food','photo' => 'category-default.jpg','slug' => 'pet-food','description' => 'Dry dog food, wet dog food, dry cat food, wet cat food, fish food, bird seed','group_by' => 'Pet Products','is_active' => '1','created_at' => '2025-05-18 20:35:02','updated_at' => '2025-05-18 20:35:02'),
            array('id' => '38','name' => 'Pet Treats','photo' => 'category-default.jpg','slug' => 'pet-treats','description' => 'Dog biscuits, catnip, chew toys, treats','group_by' => 'Pet Products','is_active' => '1','created_at' => '2025-05-18 20:35:02','updated_at' => '2025-05-18 20:35:02'),
            array('id' => '39','name' => 'Pet Medications','photo' => 'category-default.jpg','slug' => 'pet-medications','description' => 'Flea treatments, heartworm preventatives, antibiotics, supplements','group_by' => 'Pet Products','is_active' => '1','created_at' => '2025-05-18 20:35:02','updated_at' => '2025-05-18 20:35:02'),
            array('id' => '40','name' => 'Pet Care & Grooming','photo' => 'category-default.jpg','slug' => 'pet-care-grooming','description' => 'Shampoos, flea shampoos, grooming wipes, brushes, nail clippers','group_by' => 'Pet Products','is_active' => '1','created_at' => '2025-05-18 20:35:02','updated_at' => '2025-05-18 20:35:02'),
            array('id' => '41','name' => 'Pet Litter & Accessories','photo' => 'category-default.jpg','slug' => 'pet-litter-accessories','description' => 'Cat litter, litter deodorizers, pet diapers, collars, leashes, harnesses','group_by' => 'Pet Products','is_active' => '1','created_at' => '2025-05-18 20:35:02','updated_at' => '2025-05-18 20:35:02'),
            array('id' => '42','name' => 'First Aid Supplies','photo' => 'category-default.jpg','slug' => 'first-aid-supplies','description' => 'Bandages, gauze, adhesive tapes, medical wraps, cotton swabs','group_by' => 'Medical Supplies','is_active' => '1','created_at' => '2025-05-18 20:35:31','updated_at' => '2025-05-18 20:35:31'),
            array('id' => '43','name' => 'Thermometers & Blood Pressure Monitors','photo' => 'category-default.jpg','slug' => 'thermometers-monitors','description' => 'Digital thermometers, infrared thermometers, blood pressure cuffs','group_by' => 'Medical Supplies','is_active' => '1','created_at' => '2025-05-18 20:35:31','updated_at' => '2025-05-18 20:35:31'),
            array('id' => '44','name' => 'Medical Adhesives & Dressings','photo' => 'category-default.jpg','slug' => 'medical-adhesives','description' => 'Wound dressings, hydrocolloid patches, blister pads','group_by' => 'Medical Supplies','is_active' => '1','created_at' => '2025-05-18 20:35:31','updated_at' => '2025-05-18 20:35:31'),
            array('id' => '45','name' => 'Surgical & Disposable Products','photo' => 'category-default.jpg','slug' => 'surgical-products','description' => 'Syringes, needles, IV bags, disposable gloves, surgical masks','group_by' => 'Medical Supplies','is_active' => '1','created_at' => '2025-05-18 20:35:31','updated_at' => '2025-05-18 20:35:31'),
            array('id' => '46','name' => 'Pregnancy & Ovulation Tests','photo' => 'category-default.jpg','slug' => 'pregnancy-tests','description' => 'Test kits for pregnancy, ovulation, and fertility tracking','group_by' => 'Medical Supplies','is_active' => '1','created_at' => '2025-05-18 20:35:31','updated_at' => '2025-05-18 20:35:31'),
            array('id' => '47','name' => 'Batteries','photo' => 'category-default.jpg','slug' => 'electronics-batteries','description' => 'Disposable batteries (AA, AAA, C, D), lithium-ion rechargeable batteries (for phones, laptops, etc.), camera batteries','group_by' => 'Electronics & Accessories','is_active' => '1','created_at' => '2025-05-18 20:36:30','updated_at' => '2025-05-18 20:36:30'),
            array('id' => '48','name' => 'Printer Ink Cartridges','photo' => 'category-default.jpg','slug' => 'printer-ink','description' => 'Ink for printers, toner cartridges','group_by' => 'Electronics & Accessories','is_active' => '1','created_at' => '2025-05-18 20:36:30','updated_at' => '2025-05-18 20:36:30'),
            array('id' => '49','name' => 'Memory Storage Devices','photo' => 'category-default.jpg','slug' => 'memory-storage','description' => 'Flash drives, memory cards (SD cards, microSD cards)','group_by' => 'Electronics & Accessories','is_active' => '1','created_at' => '2025-05-18 20:36:30','updated_at' => '2025-05-18 20:36:30'),
            array('id' => '50','name' => 'Chargers & Cables','photo' => 'category-default.jpg','slug' => 'chargers-cables','description' => 'USB chargers, AC adapters, charging cables (smartphones, laptops)','group_by' => 'Electronics & Accessories','is_active' => '1','created_at' => '2025-05-18 20:36:30','updated_at' => '2025-05-18 20:36:30'),
            array('id' => '51','name' => 'Electronics Cleaners','photo' => 'category-default.jpg','slug' => 'electronics-cleaners','description' => 'Screen wipes, keyboard cleaning kits','group_by' => 'Electronics & Accessories','is_active' => '1','created_at' => '2025-05-18 20:36:30','updated_at' => '2025-05-18 20:36:30'),
            array('id' => '52','name' => 'Paints & Art Supplies','photo' => 'category-default.jpg','slug' => 'paints-art-supplies','description' => 'Acrylic paints, watercolor paints, oils, markers, pencils, crayons','group_by' => 'Hobby & Craft Supplies','is_active' => '1','created_at' => '2025-05-18 20:36:30','updated_at' => '2025-05-18 20:36:30'),
            array('id' => '53','name' => 'Crafting Materials','photo' => 'category-default.jpg','slug' => 'crafting-materials','description' => 'Glues, adhesives, glitter, beads, thread, yarn','group_by' => 'Hobby & Craft Supplies','is_active' => '1','created_at' => '2025-05-18 20:36:30','updated_at' => '2025-05-18 20:36:30'),
            array('id' => '54','name' => 'Sewing Supplies','photo' => 'category-default.jpg','slug' => 'sewing-supplies','description' => 'Sewing needles, fabric, sewing threads, elastic bands','group_by' => 'Hobby & Craft Supplies','is_active' => '1','created_at' => '2025-05-18 20:36:30','updated_at' => '2025-05-18 20:36:30'),
            array('id' => '55','name' => 'Cigarettes, Cigars, and Tobacco','photo' => 'category-default.jpg','slug' => 'tobacco-products','description' => 'Packaged cigarettes, loose tobacco','group_by' => 'Tobacco & Vaping Products','is_active' => '1','created_at' => '2025-05-18 20:36:30','updated_at' => '2025-05-18 20:36:30'),
            array('id' => '56','name' => 'Vaping Liquids','photo' => 'category-default.jpg','slug' => 'vaping-liquids','description' => 'E-liquids, vape cartridges, pods','group_by' => 'Tobacco & Vaping Products','is_active' => '1','created_at' => '2025-05-18 20:36:30','updated_at' => '2025-05-18 20:36:30'),
            array('id' => '57','name' => 'Nicotine Patches & Gum','photo' => 'category-default.jpg','slug' => 'nicotine-patches','description' => 'Smoking cessation aids','group_by' => 'Tobacco & Vaping Products','is_active' => '1','created_at' => '2025-05-18 20:36:30','updated_at' => '2025-05-18 20:36:30'),
            array('id' => '58','name' => 'Motor Oil & Lubricants','photo' => 'category-default.jpg','slug' => 'motor-oil-lubricants','description' => 'Engine oils, grease, transmission fluids, coolant','group_by' => 'Automotive Products','is_active' => '1','created_at' => '2025-05-18 20:36:30','updated_at' => '2025-05-18 20:36:30'),
            array('id' => '59','name' => 'Car Batteries','photo' => 'category-default.jpg','slug' => 'car-batteries','description' => 'Standard lead-acid batteries, lithium batteries','group_by' => 'Automotive Products','is_active' => '1','created_at' => '2025-05-18 20:36:30','updated_at' => '2025-05-18 20:36:30'),
            array('id' => '60','name' => 'Tire Sealants','photo' => 'category-default.jpg','slug' => 'tire-sealants','description' => 'Sealant sprays, tire repair kits','group_by' => 'Automotive Products','is_active' => '1','created_at' => '2025-05-18 20:36:30','updated_at' => '2025-05-18 20:36:30'),
            array('id' => '61','name' => 'Cleaning & Detailing Products','photo' => 'category-default.jpg','slug' => 'car-cleaning-products','description' => 'Car polish, wax, tire cleaners, windshield fluid, air fresheners','group_by' => 'Automotive Products','is_active' => '1','created_at' => '2025-05-18 20:36:30','updated_at' => '2025-05-18 20:36:30'),
            array('id' => '62','name' => 'Adhesives','photo' => 'category-default.jpg','slug' => 'adhesives','description' => 'Glue, glue sticks, tape, rubber cement','group_by' => 'Office & School Supplies','is_active' => '1','created_at' => '2025-05-18 20:36:30','updated_at' => '2025-05-18 20:36:30'),
            array('id' => '63','name' => 'Markers & Highlighters','photo' => 'category-default.jpg','slug' => 'markers-highlighters','description' => 'Permanent markers, dry erase markers, highlighters','group_by' => 'Office & School Supplies','is_active' => '1','created_at' => '2025-05-18 20:36:30','updated_at' => '2025-05-18 20:36:30'),
            array('id' => '64','name' => 'Paper Products','photo' => 'category-default.jpg','slug' => 'office-paper-products','description' => 'Printer paper, notebooks, sticky notes, post-its, envelopes','group_by' => 'Office & School Supplies','is_active' => '1','created_at' => '2025-05-18 20:36:30','updated_at' => '2025-05-18 20:36:30'),
            array('id' => '65','name' => 'Ink & Toner','photo' => 'category-default.jpg','slug' => 'ink-toner','description' => 'Printer ink cartridges, toner refills','group_by' => 'Office & School Supplies','is_active' => '1','created_at' => '2025-05-18 20:36:30','updated_at' => '2025-05-18 20:36:30'),
            array('id' => '66','name' => 'Corrective Fluids','photo' => 'category-default.jpg','slug' => 'corrective-fluids','description' => 'White-out, correction tape','group_by' => 'Office & School Supplies','is_active' => '1','created_at' => '2025-05-18 20:36:30','updated_at' => '2025-05-18 20:36:30'),
            array('id' => '67','name' => 'Petroleum-based Products','photo' => 'category-default.jpg','slug' => 'petroleum-products','description' => 'Lighter fluid, fuel additives','group_by' => 'Miscellaneous','is_active' => '1','created_at' => '2025-05-18 20:36:30','updated_at' => '2025-05-18 20:36:30'),
            array('id' => '68','name' => 'Tires & Inner Tubes','photo' => 'category-default.jpg','slug' => 'tires-inner-tubes','description' => 'Bicycle tubes, car tires (if not used on time)','group_by' => 'Miscellaneous','is_active' => '1','created_at' => '2025-05-18 20:36:30','updated_at' => '2025-05-18 20:36:30')
          );
          
        return $categories;
    }
}
